sudo: required
language: java
jdk: openjdk8

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project beefy-gainz-1555366059329
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials beefy-gainz-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  

script:
  - ./gradlew clean build

after_success:
  - docker image build -t azsuth/beefy-gainz-exercise:latest -t azsuth/beefy-gainz-exercise:$SHA .
  - docker push azsuth/beefy-gainz-exercise:latest
  - docker push azsuth/beefy-gainz-exercise:$SHA
  - kubectl apply -f k8s.yml
  - kubectl set image deployments/exercise-deployment exercise=azsuth/beefy-gainz-exercise:$SHA
