apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: exercise
  template:
    metadata:
      labels:
        component: exercise
    spec:
      containers:
        - name: exercise
          image: azsuth/beefy-gainz-exercise
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SERVER_PORT
              value: '8080'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://exercise-db-service:5432/exercise
            - name: SPRING_DATASOURCE_USERNAME
              value: exercise_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-exercise-user-password
                  key: password
            - name: WORKOUT_DURATION
              value: '4'

---

apiVersion: v1
kind: Service
metadata:
  name: exercise-service
spec:
  type: ClusterIP
  selector:
    component: exercise
  ports:
    - port: 8080
      targetPort: 8080